name: Update Sitemap

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual execution

jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for full Git history

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update sitemap with current date and time
        run: |
          CURRENT_DATETIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          cat <<EOF > sitemap.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
              <loc>https://app.acertosonline.com/</loc>
              <lastmod>$CURRENT_DATETIME</lastmod>
              <changefreq>always</changefreq>
              <priority>1.0</priority>
            </url>
            <url>
              <loc>https://app.acertosonline.com/palpites</loc>
              <lastmod>$CURRENT_DATETIME</lastmod>
              <changefreq>always</changefreq>
              <priority>1.0</priority>
            </url>
          </urlset>
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sitemap.xml
          git commit -m "Update sitemap lastmod to $CURRENT_DATETIME" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ping Google
        run: |
          curl "http://www.google.com/ping?sitemap=https://app.acertosonline.com/sitemap.xml"
